### ISSUE TITLE
ipython notebookをALPSソースに含める

### ISSUE THREAD

**Issue by wistaria** [cmsi/alps-tutorial#48]

**Comment by halm** [comment]
ALPS の svnリポジトリにはだいぶ前に tutorials/ 以下に *.ipynb を加えてあります．

**Comment by wistaria** [comment]
alps-tutorialsのnotebookディレクトリにあるものと、ALPSのtutorialsにあるものとでは、どちらがより新しいですか？ALPSのtutorialsの方が最新版であることを確認して、alps-tutorialsの方を削除してください。お願いします。

**Comment by halm** [comment]
日本語版のnotebookもALPSへ含めますか?

英語版のnotebookは alps/tutorials/ 以下のそれぞれのチュートリアルのディレクトリに置いてあります．
日本語版の方はパラメータファイル名を変更してあるので同じ場所に置くのは難しいです．

それと，とりあえずdevelopブランチではALPS mediawiki にあるチュートリアルの notebook は削除し， notebook/jp/crash_course_pyalps.ipynb,python.ipynb の 2 ファイルだけ残しました．

**Comment by wistaria** [comment]
python notebook は全てのチュートリアルが同じディレクトリにある方が使いやすいですね。
alps/tutorials の下に notebook/en と notebook/ja を作って、そこにまとめてはどうでしょう？

alps-tutorial の方は、notebook/jp/crash_course_pyalps.ipynb, python.ipynb を pyalps, python の下に戻して、スライドと一緒に配布するようにします。

**Comment by halm** [comment]
ipynb を ALPS の tutorial/notebook/en,ja に移動しました．

**Comment by wistaria** [comment]
ありがとうございます。
alps/tutorials を https://github.com/cmsi/alps-tutorial/tree/tutorials に取り込みました。
https://github.com/cmsi/alps-tutorial/archive/tutorials.zip で最新版の tutorials がダウンロードできます。
また、tutorial PDF からこの中のファイルにリンクをはることで、チュートリアルの中身を表示するのも簡単になります。
