### ISSUE TITLE
ターミナルでmatplotlibを使いたい人に

### ISSUE THREAD

**Issue by halm** [cmsi/alps-tutorial#49]
ターミナルで作業したい人は次のコマンド(ion) を打つと作業がはかどる．
gnuplot のようにコマンドを打ちつつ描画させることができるようになる．
チュートリアルのどこかで紹介する．

```python
import matplotlib.pyplot as plt
plt.ion()
```

あと `plt.clf(), plt.cla()` も覚えておくと良い．それぞれfigureのクリア，axisのクリア

**Comment by wistaria** [comment]
0164718e8972b04258413cdf40e019c163cf4ef9 で追加
